openapi: 3.0.0
info:
  version: 1.0.0
  title: Mechalink Api
  description: Connecting clients with mechanics
servers:
  - url: https://1npaj0q9ug.execute-api.eu-west-1.amazonaws.com
components:
  schemas: {}
  parameters: {}
paths:
  /jobs:
    get:
      summary: Get a single user
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        "200":
          description: Object with user data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  age:
                    type: number
                required:
                  - id
                  - name
                  - age
                example:
                  name: "1212121"
                  id: "1"
                  age: 1
