openapi: 3.0.0
info:
  version: 1.0.0
  title: My API
  description: This is the API
servers:
  - url: http://localhost:3000
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "1212121"
        name:
          type: string
          example: John Doe
        age:
          type: number
          example: 42
      required:
        - id
        - name
        - age
    User2:
      type: object
      properties:
        id:
          type: string
          example: "1212121"
        name:
          type: string
          example: John Doe
        age:
          type: number
          example: 42
      required:
        - id
        - name
        - age
  parameters: {}
paths:
  /users/{id}:
    get:
      summary: Get a single user
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        "200":
          description: Object with user data.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /users:
    get:
      summary: Get a single user
      parameters:
        - schema:
            type: string
          required: true
          name: id
          in: path
      responses:
        "204":
          description: Object with user data 2.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User2"
